/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import main.coder.*;

/**
 *
 * @author zaidi
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JLabel();
        settingsButton = new javax.swing.JLabel();
        decodeButton = new javax.swing.JLabel();
        encodeButton = new javax.swing.JLabel();
        backgroundOpacity = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        exitButton.setForeground(new java.awt.Color(242, 243, 244));
        exitButton.setText("Exit");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitButtonMouseReleased(evt);
            }
        });
        add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        settingsButton.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(242, 243, 244));
        settingsButton.setText("Settings");
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                settingsButtonMouseReleased(evt);
            }
        });
        add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        decodeButton.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        decodeButton.setForeground(new java.awt.Color(242, 243, 244));
        decodeButton.setText("Decode");
        decodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decodeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decodeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                decodeButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                decodeButtonMouseReleased(evt);
            }
        });
        add(decodeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        encodeButton.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        encodeButton.setForeground(new java.awt.Color(242, 243, 244));
        encodeButton.setText("Encode");
        encodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encodeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encodeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                encodeButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                encodeButtonMouseReleased(evt);
            }
        });
        add(encodeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        backgroundOpacity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background50Opacity 1280x720.png"))); // NOI18N
        add(backgroundOpacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EnigmaBackground 1280x720.png"))); // NOI18N
        add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void encodeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encodeButtonMouseEntered
        encodeButton.setForeground(new java.awt.Color(179, 179, 179));
    }//GEN-LAST:event_encodeButtonMouseEntered

    private void encodeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encodeButtonMouseExited
        encodeButton.setForeground(new java.awt.Color(242, 243, 244));
    }//GEN-LAST:event_encodeButtonMouseExited

    private void encodeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encodeButtonMousePressed
        encodeButton.setForeground(new java.awt.Color(69, 69, 71));
    }//GEN-LAST:event_encodeButtonMousePressed

    private void encodeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encodeButtonMouseReleased
        encodeButton.setForeground(new java.awt.Color(242, 243, 244));
        
        CoderPanel panel = new CoderPanel();
        panel.setHeader("Encode Message");
        main.PanelSwapper.getInstance().showPanel(panel);
    }//GEN-LAST:event_encodeButtonMouseReleased

    private void decodeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decodeButtonMouseEntered
        decodeButton.setForeground(new java.awt.Color(179, 179, 179));
    }//GEN-LAST:event_decodeButtonMouseEntered

    private void decodeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decodeButtonMouseExited
        decodeButton.setForeground(new java.awt.Color(242, 243, 244));
    }//GEN-LAST:event_decodeButtonMouseExited

    private void decodeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decodeButtonMousePressed
        decodeButton.setForeground(new java.awt.Color(69, 69, 71));
    }//GEN-LAST:event_decodeButtonMousePressed

    private void decodeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decodeButtonMouseReleased
        decodeButton.setForeground(new java.awt.Color(242, 243, 244));
        
        CoderPanel panel = new CoderPanel();
        panel.setHeader("Decode Message");
        main.PanelSwapper.getInstance().showPanel(panel);
    }//GEN-LAST:event_decodeButtonMouseReleased

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        settingsButton.setForeground(new java.awt.Color(179, 179, 179));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        settingsButton.setForeground(new java.awt.Color(242, 243, 244));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void settingsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMousePressed
        settingsButton.setForeground(new java.awt.Color(69, 69, 71));
    }//GEN-LAST:event_settingsButtonMousePressed

    private void settingsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseReleased
        settingsButton.setForeground(new java.awt.Color(242, 243, 244));
        
        main.PanelSwapper.getInstance().showSettingsPanel();
    }//GEN-LAST:event_settingsButtonMouseReleased

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setForeground(new java.awt.Color(179, 179, 179));
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setForeground(new java.awt.Color(242, 243, 244));
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        exitButton.setForeground(new java.awt.Color(69, 69, 71));
    }//GEN-LAST:event_exitButtonMousePressed

    private void exitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseReleased
        exitButton.setForeground(new java.awt.Color(242, 243, 244));
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel backgroundOpacity;
    private javax.swing.JLabel decodeButton;
    private javax.swing.JLabel encodeButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel settingsButton;
    // End of variables declaration//GEN-END:variables
}
